### ISSUE TITLE
Fix UNet interactivity UI

### ISSUE THREAD

**Issue by michaels10** [junlabucsd/napari-mm3#16]
The Unet threshold interactivity UI needs an overhaul. In particular:

* A preview should be automatically displayed upon specifying a model.
* Preview should be dynamic (use the threshold) by default.
* Preview should allow the user to change peak/FOV.

**Comment by michaels10** [comment]
OK, so I've taken a look at the work required. This fix will require the following steps:

* Pull the UNet prediction and the postprocessing out into separate functions.
* Prevent the user from changing the threshold before they specify the model.
* Upon specifying the model, auto-load the first peak (with the threshold as interactive)
* Allow the user to change FOV/peak within the preview.

**Comment by michaels10** [comment]
@rthiermann Could you pull out the postprocessing/unet analysis? It's a little wonky.

**Comment by rthiermann** [comment]
I've pushed an update with the pre and post-processing functions separated from the main segmentation.
