### ISSUE TITLE
Fill out the unet pipeline

### ISSUE THREAD

**Issue by michaels10** [junlabucsd/napari-mm3#26]
The Unet pipeline needs some work. Currently, we only have annotate and unet segmentation, with no way of generating the model (we leave that to the user). We think the best way to fix this is:
* Add an ipython notebook. This notebook should launch napari for annotation, and for segmentation. It should create the model, and potentially feed it into napari.
* Update the docs accordingly.

**Comment by rthiermann** [comment]
We now have a notebook and also a training widget (user can choose which to use). Both are now described in the docs.
