### ISSUE TITLE
Channel picker too wide

### ISSUE THREAD

**Issue by ka-1999** [junlabucsd/napari-mm3#36]
I've been trying to get familiar with this plugin and have been trying to get it to work on some mother machine data from my lab. I haven't been able to get past the TIFFConverter and Compile steps though. They run fine but then I get to the channel picker and it gives me huge sections to choose from that cover many channels rather than just one. I've tried using my own tiffs, starting over the whole process with a .nd2 file, changing the channel width and separation values but nothing seems to be changing the outcome for me. How can I fix this? 

I've attached a screenshot of the channel picker and the contents of what was in the analysis folder.

Sorry if this is a dumb question, I've new to this kind of software.
Thanks in advance!

![Screenshot of channel picker](https://github.com/junlabucsd/napari-mm3/assets/111235105/e9e60776-a1af-4bf3-8eb3-40b4dcd7bade)
[channel_masks.txt](https://github.com/junlabucsd/napari-mm3/files/12648502/channel_masks.txt)
[crosscorrs.txt](https://github.com/junlabucsd/napari-mm3/files/12648503/crosscorrs.txt)
[TIFF_metadata.txt](https://github.com/junlabucsd/napari-mm3/files/12648504/TIFF_metadata.txt)

**Comment by rthiermann** [comment]
Hi,

Not a dumb question! The channel picker struggles sometimes when there are large regions without any channels in the image. Can you try cropping out the empty right hand region and running it again?

**Comment by ka-1999** [comment]
Hello!
Is there a simple way to crop in the x-axis for all the TIFFs created from the TIFFconverter?
Thank you!

Edit: I fixed it! There was a lovely crop plugin and time splitter that I was able to use to cut the image down. It totally worked!
Thank you again!

**Comment by rthiermann** [comment]
Glad you got it working! In any case, this got me to add the option to crop along the x axis in TIFFconverter - if you pull the current version and relaunch napari (no need to reinstall the plugin) it should show up.

**Comment by rthiermann** [comment]
Added x-axis cropping in TIFFConverter (still needs interactivity though)
