### ISSUE TITLE
Napari 0.5.0 incompatible

### ISSUE THREAD

**Issue by acJuarez** [junlabucsd/napari-mm3#39]
Attempted install process but encountered dependency conflicts with the new released version of napari version 0.5.0. Dependency conflict arose from tifffile version 2021.11.2 not working with the new version of napari. Fixed by setting napari version to 0.4.19. Current install steps downloads most recent version of napari and could cause install issues for new users

**Comment by michaels10** [comment]
Hi! Thanks for the detailed report, I'll fix it up once I'm done with candidacy (in ~1 mo)
